# Generated by Django 3.1.8 on 2021-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictators_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.TextField()),
                ('password_salt', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GameBoard',
        ),
    ]
