# Generated by Django 3.1.8 on 2021-07-20 00:29

import dictators.dictators_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictators_game', '0004_auto_20210717_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('replay_data', models.TextField()),
                ('participants', models.ManyToManyField(related_name='participants', to='dictators_game.User')),
                ('winner', models.ForeignKey(on_delete=models.SET(dictators.dictators_game.models.get_sentinel_user), to='dictators_game.user')),
            ],
        ),
    ]
