# Generated by Django 3.1.8 on 2021-07-20 00:47

import dictators.dictators_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictators_game', '0005_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='replay_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=models.SET(dictators.dictators_game.models.get_sentinel_user), to='dictators_game.user'),
        ),
    ]
